#!/usr/bin/env python3
"""Generate wine/x86_64 leaf elements from canonical aarch64 recipes.

Canonical elements under buildstream/elements/ remain the source of truth for
package version, sources, and build options. This script rewrites a small
whitelist into wine/x86_64/ with:

  - target-triple: x86_64-linux-android35
  - conf-global: --host=x86_64-linux-android  (autotools only, when present/needed)
  - depends filenames rewritten into wine/x86_64/ when a generated or existing
    wine sibling would be required (leaf packages in the whitelist have none)

Architecture-independent shared packages are listed in
wine-x86_64-shared.txt and must not be generated here.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ELEMENTS = ROOT / "elements"
WINE = ELEMENTS / "wine" / "x86_64"
SHARED_LIST = ROOT / "wine-x86_64-shared.txt"
GENERATED_LIST = ROOT / "wine-x86_64-generated.txt"
TARGET_TRIPLE = "x86_64-linux-android35"
CONF_GLOBAL = "--host=x86_64-linux-android"
MARKER = (
    "# Generated by buildstream/sync-wine-x86_64.py — edit the canonical "
    "element, then re-run the sync.\n"
)


def read_list(path: Path) -> list[str]:
    entries: list[str] = []
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            entries.append(line)
    return entries


def inject_wine_variables(text: str, kind: str) -> str:
    """Insert/replace wine target variables while preserving other variables."""
    wine_vars = [f"  target-triple: {TARGET_TRIPLE}"]
    if kind.strip() == "autotools":
        wine_vars.append(f"  conf-global: {CONF_GLOBAL}")

    if re.search(r"(?m)^variables:\s*$", text):
        # Drop previous generated overrides if re-running.
        text = re.sub(
            rf"(?m)^  target-triple:.*\n(?:  conf-global: {re.escape(CONF_GLOBAL)}\n)?",
            "",
            text,
        )
        block = "variables:\n" + "\n".join(wine_vars) + "\n"
        text = re.sub(r"(?m)^variables:\s*\n", block, text, count=1)
        return text

    # No variables block — insert before config:/environment:/sources end.
    block = "variables:\n" + "\n".join(wine_vars) + "\n\n"
    match = re.search(r"(?m)^(config|environment):", text)
    if match:
        return text[: match.start()] + block + text[match.start() :]
    return text.rstrip() + "\n\n" + block


def rewrite_depends(text: str, shared: set[str]) -> str:
    """Point intra-graph depends at wine/x86_64 siblings unless shared."""

    def repl(match: re.Match[str]) -> str:
        name = match.group(1)
        if (
            name.startswith("host/")
            or name.startswith("toolchains/")
            or name.startswith("wine/")
            or name in shared
        ):
            return match.group(0)
        wine_path = WINE / name
        canonical = ELEMENTS / name
        if wine_path.exists() or canonical.exists():
            # Prefer wine sibling when this package is part of the wine graph.
            if wine_path.exists() or name in read_list(GENERATED_LIST):
                return f"filename: wine/x86_64/{name}"
        return match.group(0)

    return re.sub(r"filename:\s*([^\s]+)", repl, text)


def generate_one(rel: str, shared: set[str]) -> str:
    canonical = ELEMENTS / rel
    if not canonical.is_file():
        raise SystemExit(f"missing canonical element: {rel}")
    text = canonical.read_text()
    kind_match = re.match(r"kind:\s*(\S+)", text)
    kind = kind_match.group(1) if kind_match else ""
    text = rewrite_depends(text, shared)
    text = inject_wine_variables(text, kind)
    if not text.startswith(MARKER):
        text = MARKER + text
    # Neutralize aarch64-only wording in descriptions when present.
    text = text.replace("aarch64-linux-android26", TARGET_TRIPLE)
    return text


def check_shared(shared: list[str]) -> list[str]:
    errors: list[str] = []
    for rel in shared:
        wine_copy = WINE / rel
        if wine_copy.exists():
            errors.append(f"shared element must not exist under wine/x86_64: {rel}")
        canonical = ELEMENTS / rel
        if not canonical.is_file():
            errors.append(f"shared canonical element missing: {rel}")
    # Ensure wine graph references use canonical names for shared packages.
    for path in WINE.rglob("*.bst"):
        text = path.read_text()
        for rel in shared:
            if f"wine/x86_64/{rel}" in text:
                errors.append(
                    f"{path.relative_to(ELEMENTS)} still depends on wine/x86_64/{rel}"
                )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files and shared-element invariants without writing",
    )
    args = parser.parse_args()

    shared = read_list(SHARED_LIST)
    generated = read_list(GENERATED_LIST)
    shared_set = set(shared)

    errors = check_shared(shared)
    planned: dict[str, str] = {}
    for rel in generated:
        planned[rel] = generate_one(rel, shared_set)

    if args.check:
        for rel, content in planned.items():
            path = WINE / rel
            if not path.is_file():
                errors.append(f"missing generated wine element: {rel}")
                continue
            current = path.read_text()
            if current != content:
                errors.append(f"generated wine element out of date: {rel}")
        if errors:
            print("\n".join(errors), file=sys.stderr)
            return 1
        print(
            f"ok: {len(shared)} shared, {len(generated)} generated wine/x86_64 elements"
        )
        return 0

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    for rel, content in planned.items():
        path = WINE / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
