#!/usr/bin/env python3
"""Generate arch-specific BuildStream elements from platform-agnostic recipes.

Source of truth: buildstream/recipes/<path>  (NOT under element-path)

Emits:
  buildstream/elements/<path>               # imagefs / project.conf defaults
  buildstream/elements/wine/x86_64/<path>   # Proton Wine x86_64 overrides

BuildStream never reads recipes/ directly. Edit a recipe, run this script,
commit both generated element trees, then `bst build` as usual.

Shared arch-independent packages (headers/proto) stay as plain elements and
are listed in wine-x86_64-shared.txt — wine depends on those canonical paths.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RECIPES = ROOT / "recipes"
ELEMENTS = ROOT / "elements"
WINE = ELEMENTS / "wine" / "x86_64"
RECIPE_LIST = ROOT / "arch-recipes.txt"
SHARED_LIST = ROOT / "wine-x86_64-shared.txt"

WINE_TRIPLE = "x86_64-linux-android35"
WINE_CONF_GLOBAL = "--host=x86_64-linux-android"

IMAGEFS_MARKER = (
    "# Generated by buildstream/sync-arch-elements.py from "
    "buildstream/recipes/ — edit the recipe, then re-run the sync.\n"
)
WINE_MARKER = IMAGEFS_MARKER


def read_list(path: Path) -> list[str]:
    entries: list[str] = []
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            entries.append(line)
    return entries


def strip_recipe_header(text: str) -> str:
    """Drop human recipe banners; generated elements get their own marker."""
    lines = text.splitlines(True)
    while lines and lines[0].lstrip().startswith("#"):
        # Keep YAML comments that are not the recipe banner? Banner is first
        # contiguous comment block before `kind:`.
        if lines[0].startswith("kind:"):
            break
        first = lines[0]
        lines = lines[1:]
        if not first.strip():
            break
        # Stop if we hit a non-banner structural comment unexpectedly
        if first.startswith("#") and "kind:" in "".join(lines[:5]):
            continue
    # Re-skip blank lines after header
    while lines and lines[0].strip() == "":
        lines.pop(0)
    body = "".join(lines)
    if not re.match(r"kind:\s*\S+", body):
        raise SystemExit("recipe body does not start with kind:")
    return body


def inject_variables(text: str, kind: str, *, wine: bool) -> str:
    if not wine:
        return text

    wine_vars = [f"  target-triple: {WINE_TRIPLE}"]
    if kind == "autotools":
        wine_vars.append(f"  conf-global: {WINE_CONF_GLOBAL}")

    if re.search(r"(?m)^variables:\s*$", text):
        text = re.sub(
            rf"(?m)^  target-triple:.*\n(?:  conf-global: {re.escape(WINE_CONF_GLOBAL)}\n)?",
            "",
            text,
        )
        block = "variables:\n" + "\n".join(wine_vars) + "\n"
        return re.sub(r"(?m)^variables:\s*\n", block, text, count=1)

    block = "variables:\n" + "\n".join(wine_vars) + "\n\n"
    match = re.search(r"(?m)^(config|environment):", text)
    if match:
        return text[: match.start()] + block + text[match.start() :]
    return text.rstrip() + "\n\n" + block


def rewrite_depends(text: str, shared: set[str], recipes: set[str], *, wine: bool) -> str:
    if not wine:
        return text

    def repl(match: re.Match[str]) -> str:
        name = match.group(1)
        if (
            name.startswith("host/")
            or name.startswith("toolchains/")
            or name.startswith("wine/")
            or name in shared
        ):
            return match.group(0)
        if (WINE / name).exists() or name in recipes:
            return f"filename: wine/x86_64/{name}"
        return match.group(0)

    return re.sub(r"filename:\s*([^\s]+)", repl, text)


def render(rel: str, shared: set[str], recipes: set[str], *, wine: bool) -> str:
    recipe_path = RECIPES / rel
    if not recipe_path.is_file():
        raise SystemExit(f"missing recipe: {recipe_path}")
    body = strip_recipe_header(recipe_path.read_text())
    kind_match = re.match(r"kind:\s*(\S+)", body)
    kind = kind_match.group(1) if kind_match else ""
    body = rewrite_depends(body, shared, recipes, wine=wine)
    body = inject_variables(body, kind, wine=wine)
    marker = WINE_MARKER if wine else IMAGEFS_MARKER
    return marker + body


def check_shared(shared: list[str]) -> list[str]:
    errors: list[str] = []
    for rel in shared:
        if (WINE / rel).exists():
            errors.append(f"shared element must not exist under wine/x86_64: {rel}")
        if not (ELEMENTS / rel).is_file():
            errors.append(f"shared canonical element missing: {rel}")
        if (RECIPES / rel).exists():
            errors.append(
                f"shared package {rel} should stay as a plain element, not a dual-arch recipe"
            )
    for path in WINE.rglob("*.bst"):
        text = path.read_text()
        for rel in shared:
            if f"wine/x86_64/{rel}" in text:
                errors.append(
                    f"{path.relative_to(ELEMENTS)} still depends on wine/x86_64/{rel}"
                )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated elements match recipes without writing",
    )
    args = parser.parse_args()

    shared = read_list(SHARED_LIST)
    recipes = read_list(RECIPE_LIST)
    shared_set = set(shared)
    recipe_set = set(recipes)

    errors = check_shared(shared)
    planned: dict[tuple[str, str], str] = {}
    for rel in recipes:
        planned[("imagefs", rel)] = render(rel, shared_set, recipe_set, wine=False)
        planned[("wine", rel)] = render(rel, shared_set, recipe_set, wine=True)

    if args.check:
        for (kind, rel), content in planned.items():
            path = (WINE / rel) if kind == "wine" else (ELEMENTS / rel)
            if not path.is_file():
                errors.append(f"missing generated {kind} element: {rel}")
                continue
            if path.read_text() != content:
                errors.append(f"generated {kind} element out of date: {rel}")
        if errors:
            print("\n".join(errors), file=sys.stderr)
            return 1
        print(
            f"ok: {len(shared)} shared, {len(recipes)} dual-arch recipes "
            f"({len(recipes) * 2} generated elements)"
        )
        return 0

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    for (kind, rel), content in planned.items():
        path = (WINE / rel) if kind == "wine" else (ELEMENTS / rel)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
